### ISSUE TITLE
Stuck at pending with new version

### ISSUE THREAD

**Issue by Logicman111** [openshift/metallb-operator#131]
Hi, I get this error in the subscription tab and it's stuck at pending in Openshift 4.11.21

error validating existing CRs against new CRD's schema for "addresspools.metallb.io": error listing resources in GroupVersionResource schema.GroupVersionResource{Group:"metallb.io", Version:"v1alpha1", Resource:"addresspools"}: conversion webhook for metallb.io/v1beta1, Kind=AddressPool failed: no kind "AddressPool" is registered for version "metallb.io/v1alpha1" in scheme "/metallb/internal/k8s/k8s.go:59"

I deleted the address pool that I had, but the error still there.

**Comment by 9techijcore** [comment]
Hello, we have same issue any idea ? Thanks

**Comment by sastorsl** [comment]
A fix have come for this I think, but a workaround is to delete the addresspool and re-apply it.
