### ISSUE TITLE
Filter lists in FRR are duplicated

### ISSUE THREAD

**Issue by yellowpattern** [openshift/metallb-operator#171]
When I examine the frr.conf files that get generated, I see duplicated ACLs.

In this example, 10.1.1.1 and 10.1.2.1 are BGP peers.

The IP#s 192.168.1.10 - 192.168.1.18 represent advertised IP addresses from IPAddressPools that are advertised.

ip prefix-list 10.1.1.1-pl-ipv4 seq 5 permit 192.168.1.10/32
ip prefix-list 10.1.1.1-pl-ipv4 seq 10 permit 192.168.1.11/32
ip prefix-list 10.1.1.1-pl-ipv4 seq 15 permit 192.168.1.12/32
ip prefix-list 10.1.1.1-pl-ipv4 seq 20 permit 192.168.1.13/32
ip prefix-list 10.1.1.1-pl-ipv4 seq 25 permit 192.168.1.14/32
ip prefix-list 10.1.1.1-pl-ipv4 seq 30 permit 192.168.1.15/32
ip prefix-list 10.1.1.1-pl-ipv4 seq 35 permit 192.168.1.16/32
ip prefix-list 10.1.1.1-pl-ipv4 seq 40 permit 192.168.1.17/32
ip prefix-list 10.1.1.1-pl-ipv4 seq 45 permit 192.168.1.18/32
ip prefix-list 10.1.1.1-pl-ipv4 seq 50 deny any
ip prefix-list 10.1.1.1-pl-ipv4 seq 55 permit 192.168.1.11/32
ip prefix-list 10.1.1.1-pl-ipv4 seq 60 permit 192.168.1.12/32
ip prefix-list 10.1.1.1-pl-ipv4 seq 65 permit 192.168.1.13/32
ip prefix-list 10.1.1.1-pl-ipv4 seq 70 permit 192.168.1.14/32
ip prefix-list 10.1.1.1-pl-ipv4 seq 75 permit 192.168.1.15/32
ip prefix-list 10.1.1.1-pl-ipv4 seq 80 permit 192.168.1.16/32
ip prefix-list 10.1.1.1-pl-ipv4 seq 85 permit 192.168.1.17/32
ip prefix-list 10.1.1.1-pl-ipv4 seq 90 permit 192.168.1.18/32
ip prefix-list 10.1.1.1-pl-ipv4 seq 95 permit 192.168.1.19/32
ip prefix-list 10.1.1.1-pl-ipv4 seq 100 deny any
ip prefix-list 10.1.1.1-pl-ipv4 seq 105 permit 192.168.1.11/32
ip prefix-list 10.1.1.1-pl-ipv4 seq 110 permit 192.168.1.12/32
ip prefix-list 10.1.1.1-pl-ipv4 seq 115 permit 192.168.1.13/32
ip prefix-list 10.1.1.1-pl-ipv4 seq 120 permit 192.168.1.14/32
ip prefix-list 10.1.1.1-pl-ipv4 seq 125 permit 192.168.1.15/32
ip prefix-list 10.1.1.1-pl-ipv4 seq 130 permit 192.168.1.16/32
ip prefix-list 10.1.1.1-pl-ipv4 seq 135 permit 192.168.1.17/32
ip prefix-list 10.1.1.1-pl-ipv4 seq 140 permit 192.168.1.18/32
ip prefix-list 10.1.1.1-pl-ipv4 seq 145 permit 192.168.1.19/32
ip prefix-list 10.1.1.1-pl-ipv4 seq 150 deny any
ip prefix-list 10.1.2.1-pl-ipv4 seq 5 deny any
ip prefix-list 10.1.2.1-pl-ipv4 seq 10 deny any
ip prefix-list 10.1.2.1-pl-ipv4 seq 15 deny any
!
ipv6 prefix-list 10.1.1.1-pl-ipv4 seq 5 deny any
ipv6 prefix-list 10.1.1.1-pl-ipv4 seq 10 deny any
ipv6 prefix-list 10.1.1.1-pl-ipv4 seq 15 deny any
ipv6 prefix-list 10.1.2.1-pl-ipv4 seq 5 deny any
ipv6 prefix-list 10.1.2.1-pl-ipv4 seq 10 deny any
ipv6 prefix-list 10.1.2.1-pl-ipv4 seq 15 deny any

**Comment by fedepaol** [comment]
What version of metallb is this? And anyhow, can you file an issue against upstream metallb, or raise a customer case if you are an openshift user? Also, despite not being nice, this should not have impacts on metallb's functionality.

**Comment by fedepaol** [comment]
If you are eligible for support (assuming this is causing any malfunction), please file an incident.

If it's only cosmetics, we won't fix it with urgency but we may fix it upstream anyway (only on the latest version, which eventually will land on ocp).
In general, please don't mix requests for support on the community version and openshift version.

**Comment by yellowpattern** [comment]
This isn't for the Red Hat Openshift metallb?

**Comment by fedepaol** [comment]
this is a github issue, which is not hte proper way to raise incidents to Red Hat

**Comment by fedepaol** [comment]
plus, I iterate, if metallb works properly despite the repetition, this won't likely to be fixed as it's an internal detail.
Said that, either file a customer case if metallb's functionality is compromised or file an upstream issue which will be handled in a best effort manner.

**Comment by fedepaol** [comment]
> What's the point of this issue register then? Redhat tickets is where customer issues go to disappear into a void of offshore support.

I hope it's clear I am trying to help here, and as I wrote already, this is not the right channel.

**Comment by fbaudin** [comment]
@yellowpattern, if you are a Red Hat customer and have complaints about Red Hat support, please escalate to your account manager and your Red Hat TAM. And for upstream support, just follow upstream best practices and in particular Federico's advices.  Borderline complaints behind an anonymous email will not help you to get the support that you need. And again, if you are a Red Hat customers, you will get the support level that you need :-)

**Comment by ealcaniz** [comment]
@yellowpattern  please open a ticket https://access.redhat.com/support

**Comment by yellowpattern** [comment]
I have multiple cases open with Redhat, for much simpler issues, that if I'm lucky might get closed by the end of the month. If I opened a ticket of this complexity with Redhat, going by my experiences it might be a year or more to get resolved.

**Comment by ealcaniz** [comment]
Do you mind sending me the cases number privately to ***@***.***,
please?

**Comment by yellowpattern** [comment]
I'm not sure if that would be appropriate as we've got account managers who are supposed to take care of that.
