### ISSUE TITLE
[speaker] ml_secret_key not found in metallb-operator.4.11.0-202306070816

### ISSUE THREAD

**Issue by sastorsl** [openshift/metallb-operator#172]
Referencing #165 merged into the `release-4.11` branch.

Upgrading to the `metallb-operator.4.11.0-202306070816` operator version gives an error in the speaker pods forcing us to downgrade (remove and subscribe to a specific version) of the operator.

Error message:

```json
speaker-46268 speaker {"branch":"rhaos-4.11-rhel-8","caller":"main.go:94","commit":"2109a9ce65adeb1ee00fca6c78eb8a91988f4541","goversion":"gc / go1.18.10 / amd64","level":"info","msg":"MetalLB speaker starting (commit 2109a9ce65adeb1ee00fca6c78eb8a91988f4541, branch rhaos-4.11-rhel-8)","ts":"2023-06-19T22:27:35Z","version":""}
speaker-46268 speaker {"caller":"main.go:126","error":"open /etc/ml_secret_key/secretkey: no such file or directory","level":"error","msg":"failed to read memberlist secret key file","op":"startup","ts":"2023-06-19T22:27:35Z"}
```

**Comment by fedepaol** [comment]
Please file a case https://access.redhat.com/support , we'll have a look.

**Comment by sastorsl** [comment]
Removing the old operator

```bash
# Get the currently installed version of the operator
RESULT=$(oc get clusterserviceversions.operators.coreos.com -n metallb-system | grep metallb-operator | awk '{ print $1 }')
echo ${RESULT}
 
# Delete the subscription
oc delete subscriptions.operators.coreos.com metallb-operator -n metallb-system
 
# Delete the CSV - ClusterServiceVersion - for metallb
oc delete clusterserviceversions.operators.coreos.com -n metallb-system ${RESULT}  # NB! with the value from the query above
 
# Delete the old operatorgroup for metallb BEFORE attempting to install the new one
oc -n metallb-system delete operatorgroups.operators.coreos.com --all
```

**Comment by liornoy** [comment]
Hi @sastorsl the fix for that is already out in the latest OpenShift 4.11 image.
Do you want to check if it works for you and update the status of the issue here?

**Comment by fedepaol** [comment]
This was handled in the bug mentioned above where @sastorsl already commented that it works

**Comment by liornoy** [comment]
ok great. so can we close this issue?

**Comment by fedepaol** [comment]
this is on openshift/ , we don't have control on the repo, and everytime someone mistakenly files issues here, we should redirect them either upstream or to file a case if they are RH customers.

**Comment by liornoy** [comment]
Got it, thanks for the clarification.
